version: "3.9"

services:
  jenkins:
    image: "jenkins/jenkins:2.414.3-jdk17"
    ports:
      - "2000:8080"
    restart: always
    volumes:
      - "jenkins:/var/jenkins_home"

  sonarqube:
    image: "sonarqube:lts-community"
    ports:
      - "2001:9000"
    restart: always
    volumes:
      - "sonarqube:/opt/sonarqube/data"
      - "sonarqube:/opt/sonarqube/logs"
      - "sonarqube:/opt/sonarqube/extensions"

  portainer:
    image: "portainer/portainer-ce:latest"
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "2002:9000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  agent:
    image: "portainer/agent:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]


volumes:
  jenkins:
    external: true
    name: jenkins
  sonarqube:
    external: true
    name: sonarqube
  portainer_data:
    external: true
    name: portainer_data
  


networks:
  agent_network:
    driver: overlay
    attachable: true
