- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3 
  tasks:
  - debug: var=ansible_host 

  - name: install pre-requisites
    become: true
    become_method: sudo
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 

  - name: "install python for Ansible."
    become: true
    become_method: sudo
    apt:
      name: python3
      state: latest
      update_cache: yes

  - name: "Update PiP"
    ansible.builtin.shell:
      cmd: sudo pip3 install --upgrade requests 

  - name: "s"
    kubernetes.core.k8s:
      state: absent
      api_version: v1
      kind: Service
      name: web
  