- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3 
  tasks:
  - debug: var=ansible_host 

  - name: install pre-requisites
    become: true
    become_method: sudo
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 

  - name: "install python for Ansible."
    become: true
    become_method: sudo
    apt:
      name: python3
      state: latest
      update_cache: yes
  
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'k8s/service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default

  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'k8s/deployment.yml') | from_yaml }}"