- hosts: localhost
  tasks:

  - name: Deploy the service
    become: true
    become_user: root
    ansible.builtin.shell: kubectl apply -f k8s/service.yml

  - name: Deploy the application
    become: true
    become_user: root
    ansible.builtin.shell: kubectl apply -f k8s/deployment.yml
  