- hosts: localhost
  tasks:

  - name: Deploy the service
    ansible.builtin.shell: kubectl apply -f k8s/service.yml

  - name: Deploy the application
    ansible.builtin.shell: kubectl apply -f k8s/deployment.yml
  