- hosts: localhost
  tasks:

  - name: install requirements
    ansible.builtin.shell:  pip install -r requirements.txt
  
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'k8s/service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default

  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'k8s/deployment.yml') | from_yaml }}"