- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3.8 
  tasks:
  - debug: var=ansible_host 

  - name: install pre-requisites
    become: true
    become_method: sudo
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes 

  - name: "Update PiP"
    become: true
    ansible.builtin.shell:
      cmd: sudo pip3 install --upgrade requests 

  - name: Deploy the service
    kubernetes.core.k8s:
      state: present
      src: /k8s/service.yml
      
  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'k8s/deployment.yml') | from_yaml }}"