- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3.8 
  tasks:
  - debug: var=ansible_host 

  - name: "Update PiP"
    become: true
    become_method: sudo
    ansible.builtin.shell:
      cmd:  pip3 install --upgrade requests 
        
  - name: Deploy the service
    k8s:
      state: present
      definition: "{{ lookup('template', 'k8s/service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default

  - name: Deploy the application
    k8s:
      state: present
      validate_certs: no
      namespace: default
      definition: "{{ lookup('template', 'k8s/deployment.yml') | from_yaml }}"